language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tparfitt/docker-react -f Dockerfile.dev .

script:
- docker run -e CI=true tparfitt/docker-react npm run test